name: Clima Data Automation

# Configuración para ejecutar la acción todos los días a las 00:00 UTC
on:
  schedule:
    - cron: '12 0 * * *'

jobs:
  get-weather-data:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout el código del repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    # 3. Instalar las dependencias 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    # 4. Ejecutar el script de obtención de datos meteorológicos
    - name: Run clima data script
      run: python clima.py

    # 5. Subir el archivo CSV actualizado al repositorio
    - name: Commit and push changes
      run: |
        git config --local user.email "edwarcardona86@gmail.com"
        git config --local user.name "EduardoCardona2022"
        git add clima_data.csv
        git commit -m "Updated clima data"
        git push
